using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.VisualBasic.CompilerServices;
using System.Runtime.CompilerServices;
using DXFLib.DXF;
using Microsoft.VisualBasic;

namespace DXFLib.Acad
{
	public class hwpDxf_Init
	{
		public static void BkDXF_InitDefObjValues()
		{
			hwpDxf_Vars.pnumUnitsBase = hwpDxf_Enums.UNITS_BASE.unBritish;
			BkDXF_InitDxfDimVarOrder();
			hwpDxf_Vars.padecNormal[0] = 0m;
			hwpDxf_Vars.padecNormal[1] = 0m;
			hwpDxf_Vars.padecNormal[2] = 1m;
			hwpDxf_Vars.padblNormal[0] = 0.0;
			hwpDxf_Vars.padblNormal[1] = 0.0;
			hwpDxf_Vars.padblNormal[2] = 1.0;
			hwpDxf_Vars.pdecThickness = 0m;
			hwpDxf_Vars.pdblThickness = 0.0;
			hwpDxf_Vars.pdecHeight = 0m;
			hwpDxf_Vars.pdblHeight = 0.0;
			hwpDxf_Vars.padecInsertionPoint[0] = 0m;
			hwpDxf_Vars.padecInsertionPoint[1] = 0m;
			hwpDxf_Vars.padecInsertionPoint[2] = 0m;
			hwpDxf_Vars.padblInsertionPoint[0] = 0.0;
			hwpDxf_Vars.padblInsertionPoint[1] = 0.0;
			hwpDxf_Vars.padblInsertionPoint[2] = 0.0;
			hwpDxf_Vars.pstrName = null;
			hwpDxf_Vars.pdecObliqueAngleDegree = 0m;
			hwpDxf_Vars.pdblObliqueAngleDegree = 0.0;
			hwpDxf_Vars.pdecRotationDegree = 0m;
			hwpDxf_Vars.pdblRotationDegree = 0.0;
			hwpDxf_Vars.pdecScaleFactor = 1m;
			hwpDxf_Vars.pdblScaleFactor = 1.0;
			hwpDxf_Vars.pblnDependend = false;
			hwpDxf_Vars.pblnResolved = false;
			hwpDxf_Vars.pnumTextGenerationFlag = Enums.AcTextGenerationFlag.acTextFlagNormal;
			hwpDxf_Vars.pdecWidth = 0m;
			hwpDxf_Vars.pdblWidth = 0.0;
			hwpDxf_Vars.pdecDepth = 0m;
			hwpDxf_Vars.pdblDepth = 0.0;
			hwpDxf_Vars.padecOrigin[0] = 0m;
			hwpDxf_Vars.padecOrigin[1] = 0m;
			hwpDxf_Vars.padecOrigin[2] = 0m;
			hwpDxf_Vars.padblOrigin[0] = 0.0;
			hwpDxf_Vars.padblOrigin[1] = 0.0;
			hwpDxf_Vars.padblOrigin[2] = 0.0;
			hwpDxf_Vars.pnumUCSOrthographic = Enums.AcOrthoView.acOvNone;
			hwpDxf_Vars.padecXVector[0] = 1m;
			hwpDxf_Vars.padecXVector[1] = 0m;
			hwpDxf_Vars.padecXVector[2] = 0m;
			hwpDxf_Vars.padblXVector[0] = 1.0;
			hwpDxf_Vars.padblXVector[1] = 0.0;
			hwpDxf_Vars.padblXVector[2] = 0.0;
			hwpDxf_Vars.padecYVector[0] = 0m;
			hwpDxf_Vars.padecYVector[1] = 1m;
			hwpDxf_Vars.padecYVector[2] = 0m;
			hwpDxf_Vars.padblYVector[0] = 0.0;
			hwpDxf_Vars.padblYVector[1] = 1.0;
			hwpDxf_Vars.padblYVector[2] = 0.0;
			hwpDxf_Vars.pdecViewHeight = 0m;
			hwpDxf_Vars.pdblViewHeight = 0.0;
			hwpDxf_Vars.pdecViewWidth = 0m;
			hwpDxf_Vars.pdblViewWidth = 0.0;
			hwpDxf_Vars.pdecBackClipDistance = 0m;
			hwpDxf_Vars.pdblBackClipDistance = 0.0;
			hwpDxf_Vars.pblnBackClipEnabled = false;
			hwpDxf_Vars.padecCenter[0] = 0m;
			hwpDxf_Vars.padecCenter[1] = 0m;
			hwpDxf_Vars.padblCenter[0] = 0.0;
			hwpDxf_Vars.padblCenter[1] = 0.0;
			hwpDxf_Vars.padecDirection[0] = 0m;
			hwpDxf_Vars.padecDirection[1] = 0m;
			hwpDxf_Vars.padecDirection[2] = 1m;
			hwpDxf_Vars.padblDirection[0] = 0.0;
			hwpDxf_Vars.padblDirection[1] = 0.0;
			hwpDxf_Vars.padblDirection[2] = 1.0;
			hwpDxf_Vars.pdecFrontClipDistance = 0m;
			hwpDxf_Vars.pdblFrontClipDistance = 0.0;
			hwpDxf_Vars.pblnFrontClipEnabled = false;
			hwpDxf_Vars.pdecLensLength = new decimal(50L);
			hwpDxf_Vars.pdblLensLength = 50.0;
			hwpDxf_Vars.pblnPerspectiveEnabled = false;
			hwpDxf_Vars.pnumRenderMode = hwpDxf_Enums.RENDER_MODE.rm2D;
			hwpDxf_Vars.padecTarget[0] = 0m;
			hwpDxf_Vars.padecTarget[1] = 0m;
			hwpDxf_Vars.padecTarget[2] = 0m;
			hwpDxf_Vars.padblTarget[0] = 0.0;
			hwpDxf_Vars.padblTarget[1] = 0.0;
			hwpDxf_Vars.padblTarget[2] = 0.0;
			hwpDxf_Vars.pdecViewTwistDegree = 0m;
			hwpDxf_Vars.pdblViewTwistDegree = 0.0;
			hwpDxf_Vars.pstrDescription = null;
			hwpDxf_Vars.plngBulged = 0;
			hwpDxf_Vars.pblnClosed = false;
			hwpDxf_Vars.pblnIsAnonymous = false;
			hwpDxf_Vars.pstrTextString = null;
			hwpDxf_Vars.pstrTextStyleName = "Standard";
			hwpDxf_Vars.pstrAppPath = MyProject.Application.Info.DirectoryPath;
			hwpDxf_Vars.pstrAppVersion = Conversions.ToString(MyProject.Application.Info.Version.Major) + "." + Conversions.ToString(MyProject.Application.Info.Version.Minor) + "." + Conversions.ToString(MyProject.Application.Info.Version.Revision);
			hwpDxf_Vars.pblnActive = false;
			hwpDxf_Vars.pnumActiveSpace = Enums.AcActiveSpace.acModelSpace;
			hwpDxf_Vars.pdecElevationModelSpace = 0m;
			hwpDxf_Vars.pdblElevationModelSpace = 0.0;
			hwpDxf_Vars.pdecElevationPaperSpace = 0m;
			hwpDxf_Vars.pdblElevationPaperSpace = 0.0;
			hwpDxf_Vars.pstrFullName = null;
			hwpDxf_Vars.pstrShortName = null;
			hwpDxf_Vars.padecLimits[0] = 0m;
			hwpDxf_Vars.padecLimits[1] = 0m;
			hwpDxf_Vars.padecLimits[2] = new decimal(420L);
			hwpDxf_Vars.padecLimits[3] = new decimal(297L);
			hwpDxf_Vars.padblLimits[0] = 0.0;
			hwpDxf_Vars.padblLimits[1] = 0.0;
			hwpDxf_Vars.padblLimits[2] = 420.0;
			hwpDxf_Vars.padblLimits[3] = 297.0;
			hwpDxf_Vars.pblnMSpace = false;
			hwpDxf_Vars.pblnObjectSnapMode = false;
			hwpDxf_Vars.pblnSaved = true;
			hwpDxf_Vars.pstrMenu = ".";
			hwpDxf_Vars.pdecPSVPScale = 0m;
			hwpDxf_Vars.pdblPSVPScale = 0.0;
			hwpDxf_Vars.pblnDwgTitled = false;
			hwpDxf_Vars.pblnFullOpen = true;
			hwpDxf_Vars.pstrSaveFile = null;
			hwpDxf_Vars.pstrSaveName = null;
			hwpDxf_Vars.pvarValue = null;
			hwpDxf_Vars.pstrValueString = "-";
			hwpDxf_Vars.pvarAppDefault = null;
			hwpDxf_Vars.pstrAppDefaultString = "-";
			hwpDxf_Vars.pnumLayerColor = Enums.AcColor.acWhite;
			hwpDxf_Vars.pblnFreeze = false;
			hwpDxf_Vars.pblnLayerOn = true;
			hwpDxf_Vars.pstrLayerLinetype = "Continuous";
			hwpDxf_Vars.pnumLayerLineweight = Enums.AcLineWeight.acLnWtByLwDefault;
			hwpDxf_Vars.pblnLocked = false;
			hwpDxf_Vars.pstrLayerPlotStyleName = null;
			hwpDxf_Vars.pblnPlottable = true;
			hwpDxf_Vars.pblnViewportDefault = false;
			hwpDxf_Vars.pdecPatternLength = 0m;
			hwpDxf_Vars.pdblPatternLength = 0.0;
			hwpDxf_Vars.pblnScaledToFit = false;
			hwpDxf_Vars.pdecLength = 0m;
			hwpDxf_Vars.pdblLength = 0.0;
			hwpDxf_Vars.pnumDashType = hwpDxf_Enums.DASH_TYPE.dtStandard;
			hwpDxf_Vars.pblnShapeIsUcsOriented = false;
			hwpDxf_Vars.plngShapeNumber = 0;
			hwpDxf_Vars.plngShapeStyle = -1;
			hwpDxf_Vars.pdecShapeScale = 0m;
			hwpDxf_Vars.pdblShapeScale = 0.0;
			hwpDxf_Vars.pdecShapeRotationDegree = 0m;
			hwpDxf_Vars.pdblShapeRotationDegree = 0.0;
			hwpDxf_Vars.pdecShapeOffsetX = 0m;
			hwpDxf_Vars.pdblShapeOffsetX = 0.0;
			hwpDxf_Vars.pdecShapeOffsetY = 0m;
			hwpDxf_Vars.pdblShapeOffsetY = 0.0;
			hwpDxf_Vars.pstrText = null;
			hwpDxf_Vars.pstrBigFontFile = null;
			hwpDxf_Vars.pstrFontFile = null;
			hwpDxf_Vars.pblnIsShapeFile = false;
			hwpDxf_Vars.pblnIsVertical = false;
			hwpDxf_Vars.pdecLastHeight = 0m;
			hwpDxf_Vars.pdblLastHeight = 0.0;
			hwpDxf_Vars.pdecTextWidth = 1m;
			hwpDxf_Vars.pdblTextWidth = 1.0;
			hwpDxf_Vars.pblnR12XdataSave = false;
			hwpDxf_Vars.pblnPaperSpaceView = false;
			hwpDxf_Vars.pblnUcsAssociatedToView = false;
			hwpDxf_Vars.plngArcSmoothness = 100;
			hwpDxf_Vars.pblnFastZoomsEnabled = true;
			hwpDxf_Vars.pblnFrontClipAtEye = false;
			hwpDxf_Vars.pblnGridOn = false;
			hwpDxf_Vars.pdecGridSpacingX = 0.5m;
			hwpDxf_Vars.pdblGridSpacingX = 0.5;
			hwpDxf_Vars.pdecGridSpacingY = 0.5m;
			hwpDxf_Vars.pdblGridSpacingY = 0.5;
			hwpDxf_Vars.pblnIsometricSnapEnabled = false;
			hwpDxf_Vars.padecLowerLeftCorner[0] = 0m;
			hwpDxf_Vars.padecLowerLeftCorner[1] = 0m;
			hwpDxf_Vars.padblLowerLeftCorner[0] = 0.0;
			hwpDxf_Vars.padblLowerLeftCorner[1] = 0.0;
			hwpDxf_Vars.padecSnapBasePoint[0] = 0m;
			hwpDxf_Vars.padecSnapBasePoint[1] = 0m;
			hwpDxf_Vars.padblSnapBasePoint[0] = 0.0;
			hwpDxf_Vars.padblSnapBasePoint[1] = 0.0;
			hwpDxf_Vars.pblnSnapOn = false;
			hwpDxf_Vars.pnumSnapPair = hwpDxf_Enums.SNAP_PAIR.spLeft;
			hwpDxf_Vars.pdecSnapRotationAngleDegree = 0m;
			hwpDxf_Vars.pdblSnapRotationAngleDegree = 0.0;
			hwpDxf_Vars.pdecSnapSpacingX = 0.5m;
			hwpDxf_Vars.pdblSnapSpacingX = 0.5;
			hwpDxf_Vars.pdecSnapSpacingY = 0.5m;
			hwpDxf_Vars.pdblSnapSpacingY = 0.5;
			hwpDxf_Vars.pblnUCSFollowMode = false;
			hwpDxf_Vars.pblnUCSIconAtOrigin = true;
			hwpDxf_Vars.pblnUCSIconOn = true;
			hwpDxf_Vars.pblnUCSSavedWithViewport = true;
			hwpDxf_Vars.padecUpperRightCorner[0] = 1m;
			hwpDxf_Vars.padecUpperRightCorner[1] = 1m;
			hwpDxf_Vars.padblUpperRightCorner[0] = 1.0;
			hwpDxf_Vars.padblUpperRightCorner[1] = 1.0;
			hwpDxf_Vars.pstrApplicationDescription = null;
			hwpDxf_Vars.pblnAppWasAvailable = false;
			hwpDxf_Vars.pstrOriginalClassName = null;
			hwpDxf_Vars.pstrOriginalDXFName = null;
			hwpDxf_Vars.plngProxyFlags = 0;
			hwpDxf_Vars.plngInstanceCount = 0;
			hwpDxf_Vars.pnumProxyType = hwpDxf_Enums.PROXY_TYPE.ptObject;
			hwpDxf_Vars.pstrComment = null;
			hwpDxf_Vars.pblnHasAttributeDefinitions = false;
			hwpDxf_Vars.pblnHasPreviewIcon = false;
			hwpDxf_Vars.pblnIsLayout = false;
			hwpDxf_Vars.pblnIsOverlayRef = false;
			hwpDxf_Vars.pblnIsXRef = false;
			hwpDxf_Vars.pdblLayoutObjectID = 0.0;
			hwpDxf_Vars.pstrPathName = null;
			hwpDxf_Vars.pblnIsPaperSpace = false;
			hwpDxf_Vars.pblnBlkBegEndVisible = false;
			hwpDxf_Vars.plngPaperSpace = 0;
			hwpDxf_Vars.pnumEntityColor = Enums.AcColor.acByLayer;
			hwpDxf_Vars.pstrLayer = "0";
			hwpDxf_Vars.pstrEntityLinetype = "ByLayer";
			hwpDxf_Vars.pdecLinetypeScale = 1m;
			hwpDxf_Vars.pdblLinetypeScale = 1.0;
			hwpDxf_Vars.pnumEntityLineweight = Enums.AcLineWeight.acLnWtByLayer;
			hwpDxf_Vars.pblnVisible = true;
			hwpDxf_Vars.plngRGB = -1;
			hwpDxf_Vars.pstrDictColor = null;
			hwpDxf_Vars.pblnIsPeriodic = 0.0;
			hwpDxf_Vars.padecPointNull[0] = 0m;
			hwpDxf_Vars.padecPointNull[1] = 0m;
			hwpDxf_Vars.padecPointNull[2] = 0m;
			hwpDxf_Vars.padblPointNull[0] = 0.0;
			hwpDxf_Vars.padblPointNull[1] = 0.0;
			hwpDxf_Vars.padblPointNull[2] = 0.0;
			hwpDxf_Vars.padecPointXOne[0] = 1m;
			hwpDxf_Vars.padecPointXOne[1] = 0m;
			hwpDxf_Vars.padecPointXOne[2] = 0m;
			hwpDxf_Vars.padblPointXOne[0] = 1.0;
			hwpDxf_Vars.padblPointXOne[1] = 0.0;
			hwpDxf_Vars.padblPointXOne[2] = 0.0;
			hwpDxf_Vars.pdecValueNull = 0m;
			hwpDxf_Vars.pdblValueNull = 0.0;
			hwpDxf_Vars.pdecValueOne = 1m;
			hwpDxf_Vars.pdblValueOne = 1.0;
			hwpDxf_Vars.pblnHasConstantWidth = true;
			hwpDxf_Vars.pdecConstantWidth = 0m;
			hwpDxf_Vars.pdblConstantWidth = 0.0;
			hwpDxf_Vars.pdecElevation = 0m;
			hwpDxf_Vars.pdblElevation = 0.0;
			hwpDxf_Vars.pblnLinetypeGeneration = false;
			hwpDxf_Vars.pdecCoordX = 0m;
			hwpDxf_Vars.pdblCoordX = 0.0;
			hwpDxf_Vars.pdecCoordY = 0m;
			hwpDxf_Vars.pdblCoordY = 0.0;
			hwpDxf_Vars.pdecBulge = 0m;
			hwpDxf_Vars.pdblBulge = 0.0;
			hwpDxf_Vars.pdecStartWidth = 0m;
			hwpDxf_Vars.pdblStartWidth = 0.0;
			hwpDxf_Vars.pdecEndWidth = 0m;
			hwpDxf_Vars.pdblEndWidth = 0.0;
			hwpDxf_Vars.pdecCode10 = 0m;
			hwpDxf_Vars.pdblCode10 = 0.0;
			hwpDxf_Vars.pdecCode20 = 0m;
			hwpDxf_Vars.pdblCode20 = 0.0;
			hwpDxf_Vars.pdecCode30 = 0m;
			hwpDxf_Vars.pdblCode30 = 0.0;
			hwpDxf_Vars.plngFlags66 = 1;
			hwpDxf_Vars.pblnIsCurve = false;
			hwpDxf_Vars.pblnIsSpline = false;
			hwpDxf_Vars.pblnIs3DPolyline = true;
			hwpDxf_Vars.pblnMClosed = false;
			hwpDxf_Vars.pblnSplineFitVertex = false;
			hwpDxf_Vars.pblnSplineCtlVertex = false;
			hwpDxf_Vars.pblnIsPolygonMesh = true;
			hwpDxf_Vars.pblnNClosed = false;
			hwpDxf_Vars.plngMVertexCountNumberOfVertices = 0;
			hwpDxf_Vars.plngNVertexCountNumberOfFaces = 0;
			hwpDxf_Vars.plngMDensity = 2;
			hwpDxf_Vars.plngNDensity = 2;
			hwpDxf_Vars.pblnIsPolyfaceMesh = true;
			hwpDxf_Vars.pblnIsPolyfaceMeshVertex = true;
			hwpDxf_Vars.pblnCurveFitVertex = false;
			hwpDxf_Vars.pblnIsTangentUsed = false;
			hwpDxf_Vars.pdecTangent = 0m;
			hwpDxf_Vars.pdblTangent = 0.0;
			hwpDxf_Vars.pblnIsFaceRecord = true;
			hwpDxf_Vars.plngVertex1To4 = 0;
			hwpDxf_Vars.pdecRadius = 0m;
			hwpDxf_Vars.pdblRadius = 0.0;
			hwpDxf_Vars.pdecArcStartAngleDegree = 0m;
			hwpDxf_Vars.pdblArcStartAngleDegree = 0.0;
			hwpDxf_Vars.pdecArcEndAngleDegree = 0m;
			hwpDxf_Vars.pdblArcEndAngleDegree = 0.0;
			hwpDxf_Vars.padecCoordinate[0] = 0m;
			hwpDxf_Vars.padecCoordinate[1] = 0m;
			hwpDxf_Vars.padecCoordinate[2] = 0m;
			hwpDxf_Vars.padblCoordinate[0] = 0.0;
			hwpDxf_Vars.padblCoordinate[1] = 0.0;
			hwpDxf_Vars.padblCoordinate[2] = 0.0;
			hwpDxf_Vars.pnumAlignment = Enums.AcAlignment.acAlignmentLeft;
			hwpDxf_Vars.padecTextAlignmentPoint[0] = 0m;
			hwpDxf_Vars.padecTextAlignmentPoint[1] = 1m;
			hwpDxf_Vars.padecTextAlignmentPoint[2] = 0m;
			hwpDxf_Vars.padblTextAlignmentPoint[0] = 0.0;
			hwpDxf_Vars.padblTextAlignmentPoint[1] = 1.0;
			hwpDxf_Vars.padblTextAlignmentPoint[2] = 0.0;
			hwpDxf_Vars.pnumAttachmentPoint = Enums.AcAttachmentPoint.acAttachmentPointTopLeft;
			hwpDxf_Vars.pdecActualHeight = 0m;
			hwpDxf_Vars.pdblActualHeight = 0.0;
			hwpDxf_Vars.pdecActualWidth = 0m;
			hwpDxf_Vars.pdblActualWidth = 0.0;
			hwpDxf_Vars.padecMTextDirection[0] = 1m;
			hwpDxf_Vars.padecMTextDirection[1] = 0m;
			hwpDxf_Vars.padecMTextDirection[2] = 0m;
			hwpDxf_Vars.padblMTextDirection[0] = 1.0;
			hwpDxf_Vars.padblMTextDirection[1] = 0.0;
			hwpDxf_Vars.padblMTextDirection[2] = 0.0;
			hwpDxf_Vars.pnumDrawingDirection = Enums.AcDrawingDirection.acLeftToRight;
			hwpDxf_Vars.pdecMTextHeight = 2.5m;
			hwpDxf_Vars.pdblMTextHeight = 2.5;
			hwpDxf_Vars.pdecLineSpacingFactor = 1m;
			hwpDxf_Vars.pdblLineSpacingFactor = 1.0;
			hwpDxf_Vars.pnumLineSpacingStyle = Enums.AcLineSpacingStyle.acLineSpacingStyleAtLeast;
			hwpDxf_Vars.plngBackgroundMode = 0;
			hwpDxf_Vars.pnumBackgroundFillColor = Enums.AcColor.acRed;
			hwpDxf_Vars.plngBackgroundFillRGB = -1;
			hwpDxf_Vars.plngBackgroundCode441 = 11444428;
			hwpDxf_Vars.pdecBackgroundBorderOffsetFactor = 1.5m;
			hwpDxf_Vars.pdblBackgroundBorderOffsetFactor = 1.5;
			hwpDxf_Vars.pblnTreatElementsAsHard = false;
			hwpDxf_Vars.pnumMergeStyle = hwpDxf_Enums.MERGE_STYLE.msDrcIgnore;
			hwpDxf_Vars.pstrCanonicalMediaName = null;
			hwpDxf_Vars.pblnCenterPlot = false;
			hwpDxf_Vars.pstrConfigName = null;
			hwpDxf_Vars.pblnModelType = false;
			hwpDxf_Vars.pnumPaperUnits = Enums.AcPlotPaperUnits.acInches;
			hwpDxf_Vars.pblnPlotHidden = false;
			hwpDxf_Vars.padecPlotOrigin[0] = 0m;
			hwpDxf_Vars.padecPlotOrigin[1] = 0m;
			hwpDxf_Vars.padblPlotOrigin[0] = 0.0;
			hwpDxf_Vars.padblPlotOrigin[1] = 0.0;
			hwpDxf_Vars.pnumPlotRotation = Enums.AcPlotRotation.ac0degrees;
			hwpDxf_Vars.pnumPlotType = Enums.AcPlotType.acLayout;
			hwpDxf_Vars.pblnPlotViewportBorders = false;
			hwpDxf_Vars.pblnPlotViewportsFirst = true;
			hwpDxf_Vars.pblnPlotWithLineweights = true;
			hwpDxf_Vars.pblnPlotWithPlotStyles = true;
			hwpDxf_Vars.pblnScaleLineweights = false;
			hwpDxf_Vars.pblnShowPlotStyles = false;
			hwpDxf_Vars.pnumStandardScale = Enums.AcPlotScale.ac1_1;
			hwpDxf_Vars.pstrStyleSheet = null;
			hwpDxf_Vars.pblnUseStandardScale = true;
			hwpDxf_Vars.pstrViewToPlot = null;
			hwpDxf_Vars.plngShadePlotMode = 0;
			hwpDxf_Vars.plngShadePlotResolutionLevel = 2;
			hwpDxf_Vars.plngShadePlotCustomDPI = 300;
			hwpDxf_Vars.padecPaperMarginLowerLeft[0] = 0m;
			hwpDxf_Vars.padecPaperMarginLowerLeft[1] = 0m;
			hwpDxf_Vars.padblPaperMarginLowerLeft[0] = 0.0;
			hwpDxf_Vars.padblPaperMarginLowerLeft[1] = 0.0;
			hwpDxf_Vars.padecPaperMarginUpperRight[0] = 0m;
			hwpDxf_Vars.padecPaperMarginUpperRight[1] = 0m;
			hwpDxf_Vars.padblPaperMarginUpperRight[0] = 0.0;
			hwpDxf_Vars.padblPaperMarginUpperRight[1] = 0.0;
			hwpDxf_Vars.pdecPaperWidth = 0m;
			hwpDxf_Vars.pdblPaperWidth = 0.0;
			hwpDxf_Vars.pdecPaperHeight = 0m;
			hwpDxf_Vars.pdblPaperHeight = 0.0;
			hwpDxf_Vars.padecWindowToPlotLowerLeft[0] = 0m;
			hwpDxf_Vars.padecWindowToPlotLowerLeft[1] = 0m;
			hwpDxf_Vars.padblWindowToPlotLowerLeft[0] = 0.0;
			hwpDxf_Vars.padblWindowToPlotLowerLeft[1] = 0.0;
			hwpDxf_Vars.padecWindowToPlotUpperRight[0] = 0m;
			hwpDxf_Vars.padecWindowToPlotUpperRight[1] = 0m;
			hwpDxf_Vars.padblWindowToPlotUpperRight[0] = 0.0;
			hwpDxf_Vars.padblWindowToPlotUpperRight[1] = 0.0;
			hwpDxf_Vars.pdecCustomScaleNumerator = 1m;
			hwpDxf_Vars.pdblCustomScaleNumerator = 1.0;
			hwpDxf_Vars.pdecCustomScaleDenominator = 1m;
			hwpDxf_Vars.pdblCustomScaleDenominator = 1.0;
			hwpDxf_Vars.pblnUpdatePaper = false;
			hwpDxf_Vars.pblnZoomToPaperOnUpdate = false;
			hwpDxf_Vars.pblnInitializing = false;
			hwpDxf_Vars.pblnPrevPlotInit = false;
			hwpDxf_Vars.pdecPaperScaleFactor = 1m;
			hwpDxf_Vars.pdblPaperScaleFactor = 1.0;
			hwpDxf_Vars.padecPaperImageOrigin[0] = 0m;
			hwpDxf_Vars.padecPaperImageOrigin[1] = 0m;
			hwpDxf_Vars.padblPaperImageOrigin[0] = 0.0;
			hwpDxf_Vars.padblPaperImageOrigin[1] = 0.0;
			hwpDxf_Vars.plngTabOrder = 0;
			hwpDxf_Vars.padecLayoutLimMin[0] = 0m;
			hwpDxf_Vars.padecLayoutLimMin[1] = 0m;
			hwpDxf_Vars.padblLayoutLimMin[0] = 0.0;
			hwpDxf_Vars.padblLayoutLimMin[1] = 0.0;
			hwpDxf_Vars.padecLayoutLimMax[0] = new decimal(12L);
			hwpDxf_Vars.padecLayoutLimMax[1] = new decimal(9L);
			hwpDxf_Vars.padblLayoutLimMax[0] = 12.0;
			hwpDxf_Vars.padblLayoutLimMax[1] = 9.0;
			hwpDxf_Vars.padecLayoutInsBase[0] = 0m;
			hwpDxf_Vars.padecLayoutInsBase[1] = 0m;
			hwpDxf_Vars.padecLayoutInsBase[2] = 0m;
			hwpDxf_Vars.padblLayoutInsBase[0] = 0.0;
			hwpDxf_Vars.padblLayoutInsBase[1] = 0.0;
			hwpDxf_Vars.padblLayoutInsBase[2] = 0.0;
			hwpDxf_Vars.padecLayoutExtMin[0] = 0m;
			hwpDxf_Vars.padecLayoutExtMin[1] = 0m;
			hwpDxf_Vars.padecLayoutExtMin[2] = 0m;
			hwpDxf_Vars.padblLayoutExtMin[0] = 0.0;
			hwpDxf_Vars.padblLayoutExtMin[1] = 0.0;
			hwpDxf_Vars.padblLayoutExtMin[2] = 0.0;
			hwpDxf_Vars.padecLayoutExtMax[0] = 0m;
			hwpDxf_Vars.padecLayoutExtMax[1] = 0m;
			hwpDxf_Vars.padecLayoutExtMax[2] = 0m;
			hwpDxf_Vars.padblLayoutExtMax[0] = 0.0;
			hwpDxf_Vars.padblLayoutExtMax[1] = 0.0;
			hwpDxf_Vars.padblLayoutExtMax[2] = 0.0;
			hwpDxf_Vars.pblnPsLtScale = true;
			hwpDxf_Vars.pblnLimCheck = false;
			hwpDxf_Vars.pblnFilled = false;
			hwpDxf_Vars.pnumMLineStyleColor = Enums.AcColor.acByLayer;
			hwpDxf_Vars.pdecMLineStyleStartAngleDegree = new decimal(90L);
			hwpDxf_Vars.pdblMLineStyleStartAngleDegree = 90.0;
			hwpDxf_Vars.pblnStartSquareCap = false;
			hwpDxf_Vars.pblnStartRoundCap = false;
			hwpDxf_Vars.pblnStartInnerArcs = false;
			hwpDxf_Vars.pdecMLineStyleEndAngleDegree = new decimal(90L);
			hwpDxf_Vars.pdblMLineStyleEndAngleDegree = 90.0;
			hwpDxf_Vars.pblnEndSquareCap = false;
			hwpDxf_Vars.pblnEndRoundCap = false;
			hwpDxf_Vars.pblnEndInnerArcs = false;
			hwpDxf_Vars.pblnShowMiters = false;
			hwpDxf_Vars.pdecOffset = 0m;
			hwpDxf_Vars.pdblOffset = 0.0;
			hwpDxf_Vars.pblnIsSelectable = true;
			hwpDxf_Vars.pstrAppName = null;
			hwpDxf_Vars.pintXDataType = -1;
			hwpDxf_Vars.pvarXDataValue = null;
			hwpDxf_Vars.plngObjectSchemaNumber = 0;
			hwpDxf_Vars.pdecXScaleFactor = 1m;
			hwpDxf_Vars.pdblXScaleFactor = 1.0;
			hwpDxf_Vars.pdecYScaleFactor = 1m;
			hwpDxf_Vars.pdblYScaleFactor = 1.0;
			hwpDxf_Vars.pdecZScaleFactor = 1m;
			hwpDxf_Vars.pdblZScaleFactor = 1.0;
			hwpDxf_Vars.pblnHasAttributes = false;
			hwpDxf_Vars.pdecColumnSpacing = 0m;
			hwpDxf_Vars.pdblColumnSpacing = 0.0;
			hwpDxf_Vars.pdecRowSpacing = 0m;
			hwpDxf_Vars.pdblRowSpacing = 0.0;
			hwpDxf_Vars.plngColumns = 1;
			hwpDxf_Vars.plngRows = 1;
			hwpDxf_Vars.pstrPromptString = null;
			hwpDxf_Vars.pstrTagString = null;
			hwpDxf_Vars.plngAttribFlags = 0;
			hwpDxf_Vars.pblnInvisible = false;
			hwpDxf_Vars.pblnConstant = false;
			hwpDxf_Vars.pblnVerify = false;
			hwpDxf_Vars.pblnPreset = false;
			hwpDxf_Vars.plngFieldLength = 0;
			hwpDxf_Vars.pblnSequenceEndVisible = false;
			hwpDxf_Vars.padecElevation[0] = 0m;
			hwpDxf_Vars.padecElevation[1] = 0m;
			hwpDxf_Vars.padecElevation[2] = 0m;
			hwpDxf_Vars.padblElevation[0] = 0.0;
			hwpDxf_Vars.padblElevation[1] = 0.0;
			hwpDxf_Vars.padblElevation[2] = 0.0;
			hwpDxf_Vars.pstrPatternName = "SOLID";
			hwpDxf_Vars.pblnIsSolid = true;
			hwpDxf_Vars.pblnAssociativeHatch = false;
			hwpDxf_Vars.pnumHatchStyle = Enums.AcHatchStyle.acHatchStyleNormal;
			hwpDxf_Vars.pnumPatternType = Enums.AcPatternType.acHatchPatternTypePreDefined;
			hwpDxf_Vars.pdecPatternAngle = 0m;
			hwpDxf_Vars.pdblPatternAngle = 0.0;
			hwpDxf_Vars.pdecPatternScale = 0m;
			hwpDxf_Vars.pdblPatternScale = 0.0;
			hwpDxf_Vars.pdecPatternSpace = 0m;
			hwpDxf_Vars.pdblPatternSpace = 0.0;
			hwpDxf_Vars.pblnPatternDouble = false;
			hwpDxf_Vars.pdecPixelSize = 0m;
			hwpDxf_Vars.pdblPixelSize = 0.0;
			hwpDxf_Vars.pnumLoopType = Enums.AcLoopType.acHatchLoopTypeDefault;
			hwpDxf_Vars.pblnIsDefault = true;
			hwpDxf_Vars.pblnIsExternal = false;
			hwpDxf_Vars.pblnIsPolyline = false;
			hwpDxf_Vars.pblnIsDerived = false;
			hwpDxf_Vars.pblnIsTextbox = false;
			hwpDxf_Vars.pblnIsOutermost = false;
			hwpDxf_Vars.pnumEdgeType = Enums.AcLoopEdgeType.acHatchLoopEdgeTypeUndefined;
			hwpDxf_Vars.pdecAngleDegree = 0m;
			hwpDxf_Vars.pdblAngleDegree = 0.0;
			hwpDxf_Vars.pdecBaseX = 0m;
			hwpDxf_Vars.pdblBaseX = 0.0;
			hwpDxf_Vars.pdecBaseY = 0m;
			hwpDxf_Vars.pdblBaseY = 0.0;
			hwpDxf_Vars.pdecOffsetX = 0m;
			hwpDxf_Vars.pdblOffsetX = 0.0;
			hwpDxf_Vars.pdecOffsetY = 0m;
			hwpDxf_Vars.pdblOffsetY = 0.0;
			hwpDxf_Vars.padecStartPoint[0] = 0m;
			hwpDxf_Vars.padecStartPoint[1] = 0m;
			hwpDxf_Vars.padecStartPoint[2] = 0m;
			hwpDxf_Vars.padblStartPoint[0] = 0.0;
			hwpDxf_Vars.padblStartPoint[1] = 0.0;
			hwpDxf_Vars.padblStartPoint[2] = 0.0;
			hwpDxf_Vars.padecEndPoint[0] = 0m;
			hwpDxf_Vars.padecEndPoint[1] = 0m;
			hwpDxf_Vars.padecEndPoint[2] = 0m;
			hwpDxf_Vars.padblEndPoint[0] = 0.0;
			hwpDxf_Vars.padblEndPoint[1] = 0.0;
			hwpDxf_Vars.padblEndPoint[2] = 0.0;
			hwpDxf_Vars.pdecStartAngleDegree = 0m;
			hwpDxf_Vars.pdblStartAngleDegree = 0.0;
			hwpDxf_Vars.pdecEndAngleDegree = 0m;
			hwpDxf_Vars.pdblEndAngleDegree = 0.0;
			hwpDxf_Vars.pblnIsClockWise = false;
			hwpDxf_Vars.plngDegree = 0;
			hwpDxf_Vars.pblnIsRational = false;
			hwpDxf_Vars.pdecWeight = 1m;
			hwpDxf_Vars.pdblWeight = 1.0;
			hwpDxf_Vars.pdecCoordZ = 0m;
			hwpDxf_Vars.pdblCoordZ = 0.0;
			hwpDxf_Vars.pblnIsLinear = false;
			hwpDxf_Vars.pdecKnotTolerance = 0.0000000001m;
			hwpDxf_Vars.pdblKnotTolerance = 1E-10;
			hwpDxf_Vars.pdecControlPointTolerance = 0.0000000001m;
			hwpDxf_Vars.pdblControlPointTolerance = 1E-10;
			hwpDxf_Vars.pdecFitTolerance = 0.0000000001m;
			hwpDxf_Vars.pdblFitTolerance = 1E-10;
			hwpDxf_Vars.padecStartTangent[0] = 0m;
			hwpDxf_Vars.padecStartTangent[1] = 0m;
			hwpDxf_Vars.padecStartTangent[2] = 0m;
			hwpDxf_Vars.padblStartTangent[0] = 0.0;
			hwpDxf_Vars.padblStartTangent[1] = 0.0;
			hwpDxf_Vars.padblStartTangent[2] = 0.0;
			hwpDxf_Vars.padecEndTangent[0] = 0m;
			hwpDxf_Vars.padecEndTangent[1] = 0m;
			hwpDxf_Vars.padecEndTangent[2] = 0m;
			hwpDxf_Vars.padblEndTangent[0] = 0.0;
			hwpDxf_Vars.padblEndTangent[1] = 0.0;
			hwpDxf_Vars.padblEndTangent[2] = 0.0;
			hwpDxf_Vars.pblnHasStartTangent = false;
			hwpDxf_Vars.pblnHasEndTangent = false;
		}

		public static void BkDXF_InitDxfDimVarOrder()
		{
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Clear();
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(3), "DIMPOST");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(4), "DIMAPOST");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(40), "DIMSCALE");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(41), "DIMASZ");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(42), "DIMEXO");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(43), "DIMDLI");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(44), "DIMEXE");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(45), "DIMRND");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(46), "DIMDLE");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(47), "DIMTP");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(48), "DIMTM");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(71), "DIMTOL");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(72), "DIMLIM");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(73), "DIMTIH");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(74), "DIMTOH");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(75), "DIMSE1");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(76), "DIMSE2");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(77), "DIMTAD");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(78), "DIMZIN");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(79), "DIMAZIN");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(140), "DIMTXT");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(141), "DIMCEN");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(142), "DIMTSZ");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(143), "DIMALTF");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(144), "DIMLFAC");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(145), "DIMTVP");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(146), "DIMTFAC");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(147), "DIMGAP");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(148), "DIMALTRND");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(170), "DIMALT");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(171), "DIMALTD");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(172), "DIMTOFL");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(173), "DIMSAH");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(174), "DIMTIX");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(175), "DIMSOXD");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(176), "DIMCLRD");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(177), "DIMCLRE");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(178), "DIMCLRT");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(179), "DIMADEC");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(270), "DIMUNIT");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(271), "DIMDEC");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(272), "DIMTDEC");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(273), "DIMALTU");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(274), "DIMALTTD");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(275), "DIMAUNIT");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(276), "DIMFRAC");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(277), "DIMLUNIT");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(278), "DIMDSEP");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(279), "DIMTMOVE");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(280), "DIMJUST");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(281), "DIMSD1");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(282), "DIMSD2");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(283), "DIMTOLJ");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(284), "DIMTZIN");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(285), "DIMALTZ");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(286), "DIMALTTZ");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(287), "DIMFIT");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(288), "DIMUPT");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(289), "DIMATFIT");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(340), "DIMTXSTY");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(341), "DIMLDRBLK");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(342), "DIMBLK");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(343), "DIMBLK1");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(344), "DIMBLK2");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(371), "DIMLWD");
			hwpDxf_Vars.pobjDictDxfDimVarOrder.Add(Conversions.ToString(372), "DIMLWE");
		}
	}
}
